WITH BOOK_GROUP AS (
    SELECT B.AUTHOR_ID, B.CATEGORY, SUM((B.PRICE * BS.SALES)) AS TOTAL_SALES
    FROM BOOK AS B
    JOIN BOOK_SALES AS BS
    ON B.BOOK_ID = BS.BOOK_ID
    WHERE BS.SALES_DATE LIKE '2022-01%'
    GROUP BY B.AUTHOR_ID, B.CATEGORY
)

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, BG.CATEGORY, BG.TOTAL_SALES
FROM AUTHOR AS A
JOIN BOOK_GROUP AS BG
ON A.AUTHOR_ID = BG.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC;