SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, 
       G.YEAR_MAX - D.SIZE_OF_COLONY AS YEAR_DEV, 
       ID
FROM ECOLI_DATA D
JOIN (SELECT YEAR(D.DIFFERENTIATION_DATE) AS YEAR, MAX(D.SIZE_OF_COLONY) AS YEAR_MAX
      FROM ECOLI_DATA D
      GROUP BY YEAR(D.DIFFERENTIATION_DATE)) G
ON YEAR(D.DIFFERENTIATION_DATE) = G.YEAR
ORDER BY YEAR, YEAR_DEV;