WITH MAX_SIZE_OF_COLONY AS (
    SELECT MAX(SIZE_OF_COLONY) AS YEAR_MAX, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT MS.YEAR, MS.YEAR_MAX - ED.SIZE_OF_COLONY AS YEAR_DEV, ID
FROM ECOLI_DATA ED
JOIN MAX_SIZE_OF_COLONY MS
ON YEAR(DIFFERENTIATION_DATE) = MS.YEAR
ORDER BY MS.YEAR, YEAR_DEV;