SELECT DISTINCT CRC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS CRC
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRH
ON CRC.CAR_ID = CRH.CAR_ID
WHERE CAR_TYPE = '세단' AND START_DATE LIKE '%-10-%'
ORDER BY CAR_ID DESC;