WITH HR_GRADE_GROUP AS (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY YEAR, EMP_NO
    HAVING YEAR = 2022
)

SELECT HGG.SCORE AS SCORE, HE.EMP_NO, HE.EMP_NAME, HE.POSITION, HE.EMAIL
FROM HR_EMPLOYEES HE
JOIN HR_GRADE_GROUP HGG
ON HE.EMP_NO = HGG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;